import {sanitizeSafety} from './safety.ts';
import type {SafetyReport} from './safety.ts';
import type {ModeConfig} from './modes.ts';
/** UUID v4 also works in the documented HTTP local-network demo. */
export function newId():string {
 const bytes=crypto.getRandomValues(new Uint8Array(16));
 bytes[6]=(bytes[6]&15)|64; bytes[8]=(bytes[8]&63)|128;
 const hex=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');
 return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;
}
export type Environment='DEMO'|'LIVE'|'REPLAY';
export type Scenario='cruise'|'stationary'|'channels'|'battery'|'radio'|'uart'|'internet'|'imu'|'rejection'|'failure';
export type Axis='rudder'|'elevator'|'leftAileron'|'rightAileron'|'throttle'|'aux1'|'aux2';
export const axes:Axis[]=['rudder','elevator','leftAileron','rightAileron','throttle','aux1','aux2'];
export type Inputs=Record<Axis,number>;
export type Channel={name:string;min:number;center:number;max:number;reverse:boolean;deadband:number;trim:number;subtrim:number;expo:number;rate:number};
export type Mixer={enabled:boolean;common:boolean;strength:number;differential:number;version:number;channels:Record<Axis,Channel>};
export type BatteryConfig={cells:number;chemistry:'LiPo'|'Li-ion'|'Other';warning:number;critical:number;scale:number};
export type Settings={modes?:ModeConfig;name:string;id:string;units:'g'|'ms2';mounting:string;sampleHz:number;aircraftBattery:BatteryConfig;transmitterBattery:BatteryConfig;mixer:Mixer;preflight:Record<string,boolean>;calibration:{at:string;note:string}[];browserAudio:boolean};
export type Output={normalized:number|null;pwm:number;saturated:boolean|null};
export type Vector={x:number|null;y:number|null;z:number|null};
export type Capabilities={schemaVersion:1;deviceId:string;bootId:string;firmware:{nano:string;node:string};features:Record<string,boolean>;commands:string[];maintenance:{authorized:boolean;expiresAt:number};units:{acceleration:'m/s2';angularVelocity:'deg/s';attitude:'deg';voltage:'V';pwm:'us'}};
export type Frame={sampledAt?:number|null;safety?:SafetyReport|null;schemaVersion:1;source:Environment;deviceId:string;bootId:string;seq:number;uptimeMs:number;receivedAt:number;attitude:{pitch:number|null;roll:number|null;yaw:number|null};accel:Vector;gyro:Vector;linearAcceleration:Vector|null;chipTemp:number|null;sampleHz:number|null;aircraftVoltage:number|null;transmitterVoltage:number|null;radio:{received:number;expected:number;retries:number;packetAge:number;rpd:boolean|null}|null;links:{radio:boolean|null;uart:boolean|null;wifi:boolean|null;uplink:boolean|null};wifiRssi:number|null;imu:boolean|null;armed:boolean|null;mode:string|null;inputs:Inputs|null;outputs:Partial<Record<Axis,Output>>;mixEnabled:boolean|null;configVersion:number|null;validity:Record<string,'valid'|'invalid'|'unsupported'|'not_installed'|'unknown'>};
export type DemoAudit={id:string;aircraftId:string;issuer:string;environment:'DEMO';createdAt:number;expiresAt:number;status:'Applied (simulator)'|'Rejected';reason:string;sent:false}&({kind:'servo.test';parameters:{axis:Axis;value:number}}|{kind:'parachute.deploy';parameters:{guardConfirmed:true}});
export type FlightEvent={environment?:Environment;aircraftId?:string;configuration?:Settings;command?:DemoAudit;id:string;at:number;title:string;detail:string;source:string;severity:'info'|'warning'|'critical';acknowledged:boolean;resolved:boolean};
export type Recording={id:string;name:string;notes:string;createdAt:number;source:'DEMO'|'LIVE';frames:Frame[];events:FlightEvent[];settings:Settings;saved?:boolean;seed?:boolean;sampleCount?:number};
export const zeroInputs:Inputs={rudder:0,elevator:0,leftAileron:0,rightAileron:0,throttle:0,aux1:0,aux2:0};
const channel=(name:string):Channel=>({name,min:1000,center:1500,max:2000,reverse:false,deadband:.025,trim:0,subtrim:0,expo:.2,rate:1});
export const defaultSettings:Settings={name:'Falcon 01',id:'FD-001',units:'g',mounting:'X forward · Y right · Z down',sampleHz:10,aircraftBattery:{cells:3,chemistry:'LiPo',warning:10.8,critical:10.2,scale:1},transmitterBattery:{cells:2,chemistry:'Li-ion',warning:7,critical:6.6,scale:1},mixer:{enabled:true,common:false,strength:1,differential:0,version:1,channels:{rudder:channel('Rudder'),elevator:channel('Elevator'),leftAileron:channel('Left aileron'),rightAileron:channel('Right aileron'),throttle:channel('Throttle'),aux1:channel('Auxiliary 1'),aux2:channel('Auxiliary 2')}},preflight:{},calibration:[],browserAudio:false};
export const clamp=(n:number,min=-1,max=1)=>Math.max(min,Math.min(max,n));
export const fmt=(n:number|null|undefined,d=1)=>n==null||!Number.isFinite(n)?'—':n.toFixed(d);
export const duration=(ms:number)=>`${Math.floor(Math.max(0,ms)/60000).toString().padStart(2,'0')}:${Math.floor(Math.max(0,ms)/1000%60).toString().padStart(2,'0')}`;
export function mixOutputs(inputs:Inputs,m:Mixer):Record<Axis,Output>{const v={...inputs};for(const key of axes)if(key!=='throttle'){const c=m.channels[key],a=v[key],x=Math.abs(a)<c.deadband?0:Math.sign(a)*(Math.abs(a)-c.deadband)/(1-c.deadband);v[key]=((1-c.expo)*x+c.expo*x*x*x)*c.rate;}
 if(m.enabled){const roll=v.leftAileron*m.strength,common=m.common?v.rightAileron:0;v.leftAileron=common+roll;v.rightAileron=common-roll;for(const key of ['leftAileron','rightAileron'] as Axis[])if(v[key]<0)v[key]*=1-m.differential;}
 return Object.fromEntries(axes.map(key=>{const c=m.channels[key],throttle=key==='throttle',raw=(throttle?(c.reverse?1-v[key]:v[key]):v[key]*(c.reverse?-1:1))+c.trim,normalized=clamp(raw,throttle?0:-1,1),pwm=(throttle?c.min+normalized*(c.max-c.min):c.center+normalized*(normalized<0?c.center-c.min:c.max-c.center))+c.subtrim;return [key,{normalized,pwm:Math.round(clamp(pwm,c.min,c.max)),saturated:raw!==normalized||pwm<c.min||pwm>c.max}]})) as Record<Axis,Output>;
}
export const latchMix=(previous:boolean,on:boolean,off:boolean)=>on===off?previous:on;
export function sanitizeTelemetry(frame:Frame,caps:Capabilities):Frame{
 const f=structuredClone(frame),missing=()=>({x:null,y:null,z:null});
 const invalid=(key:string)=>['invalid','unsupported','not_installed','unknown'].includes(f.validity[key]);
 if(f.imu!==true||invalid('imu')){f.attitude={pitch:null,roll:null,yaw:null};f.accel=missing();f.gyro=missing();f.linearAcceleration=null;f.chipTemp=null;f.sampleHz=null;}
 if(invalid('accel'))f.accel=missing();if(invalid('gyro'))f.gyro=missing();
 if(!caps.features.attitude||invalid('attitude'))f.attitude={pitch:null,roll:null,yaw:null};
 if(!caps.features.relativeYaw)f.attitude.yaw=null;
 if(!caps.features.linearAcceleration||invalid('linearAcceleration'))f.linearAcceleration=null;
 if(invalid('battery')||invalid('aircraftBattery'))f.aircraftVoltage=null;
 if(invalid('transmitterBattery'))f.transmitterVoltage=null;
 if(f.links.uart===false||invalid('uart')){f.inputs=null;f.outputs={};f.radio=null;f.transmitterVoltage=null;f.armed=null;f.mode=null;f.mixEnabled=null;f.configVersion=null;f.links.radio=null;}
 f.safety=sanitizeSafety(f,caps);
 return f;
}
export const auxiliaryCommand=(inside:boolean,outside:boolean)=>inside===outside?'STOP':inside?'IN':'OUT';
export function emptyFrame():Frame{return {schemaVersion:1,source:'LIVE',deviceId:'FD-001',bootId:'unknown',seq:0,uptimeMs:0,receivedAt:0,attitude:{pitch:null,roll:null,yaw:null},accel:{x:null,y:null,z:null},gyro:{x:null,y:null,z:null},linearAcceleration:null,chipTemp:null,sampleHz:null,aircraftVoltage:null,transmitterVoltage:null,radio:null,links:{radio:null,uart:null,wifi:null,uplink:null},wifiRssi:null,imu:null,armed:null,mode:null,inputs:null,outputs:{},mixEnabled:null,configVersion:null,validity:{imu:'unknown',battery:'unknown'}}}
export const scenarios:{value:Scenario;label:string}[]=[{value:'cruise',label:'Gentle roll & pitch'},{value:'stationary',label:'Stationary aircraft'},{value:'channels',label:'Channel movement'},{value:'battery',label:'Battery warning'},{value:'radio',label:'Radio packet loss'},{value:'uart',label:'UART failure'},{value:'internet',label:'Internet disconnection'},{value:'imu',label:'IMU missing'},{value:'rejection',label:'Command rejection'},{value:'failure',label:'Reported flight failure'}];
export function simulate(t:number,scenario:Scenario,s:Settings,epoch:number,manual?:Inputs):Frame{const stationary=scenario==='stationary',missing=scenario==='imu',uart=scenario!=='uart',radio=scenario!=='radio',roll=stationary?0:12*Math.sin(t/8)+3*Math.sin(t/3.4),pitch=stationary?0:4+3*Math.sin(t/6),r=roll*Math.PI/180,p=pitch*Math.PI/180;const inputs=manual??(stationary?{...zeroInputs}:{rudder:.12*Math.sin(t/7),elevator:.15*Math.sin(t/6),leftAileron:(scenario==='channels'?.85:.35)*Math.sin(t/8),rightAileron:.28*Math.sin(t/5),throttle:.62+.025*Math.sin(t/9),aux1:.1,aux2:-.2});const expected=Math.max(1,Math.floor(t*50));return {...emptyFrame(),source:'DEMO',deviceId:s.id,bootId:'sim-001',seq:Math.floor(t*s.sampleHz),uptimeMs:t*1000,receivedAt:epoch+t*1000,attitude:{pitch:missing?null:pitch,roll:missing?null:roll,yaw:missing?null:5*Math.sin(t/30)},accel:missing?{x:null,y:null,z:null}:{x:9.80665*Math.sin(p),y:-9.80665*Math.sin(r)*Math.cos(p),z:-9.80665*Math.cos(r)*Math.cos(p)},gyro:missing?{x:null,y:null,z:null}:{x:stationary?0:1.5*Math.cos(t/8)+.882*Math.cos(t/3.4),y:stationary?0:.5*Math.cos(t/6),z:stationary?0:.167*Math.cos(t/30)},chipTemp:missing?null:32.4+.2*Math.sin(t/40),sampleHz:missing?null:100,aircraftVoltage:(scenario==='battery'?10.35+.09*Math.sin(t):12.12-t*.0001-.035*Math.sin(t/4))*s.aircraftBattery.scale,transmitterVoltage:uart?(8.08-t*.00003)*s.transmitterBattery.scale:null,radio:uart?{received:Math.floor(expected*(radio?.996:.42)),expected,retries:Math.floor(expected*(radio?.004:.28)),packetAge:radio?8:1800,rpd:null}:null,links:{radio:uart?radio:null,uart,wifi:true,uplink:true},wifiRssi:-54,imu:!missing,armed:uart?!stationary:null,mode:uart?(stationary?'Maintenance':'Manual RC'):null,inputs:uart?inputs:null,outputs:uart?mixOutputs(inputs,s.mixer):{},mixEnabled:uart?s.mixer.enabled:null,configVersion:uart?s.mixer.version:null,safety:uart?{schemaVersion:1,flightFailure:scenario==='failure',failureReason:scenario==='failure'?'Simulated onboard failure report':null,readyForTakeoff:stationary,parachute:{installed:true,ready:true,state:'stowed',feedback:'deployment_sensor'}}:null,validity:{safety:uart?'valid':'unknown',imu:missing?'invalid':'valid',battery:'valid',navigation:'not_installed',linearAcceleration:'unsupported'}}}
export const demoCapabilities:Capabilities={schemaVersion:1,deviceId:'FD-001',bootId:'sim-001',firmware:{nano:'sim-nano/1.0',node:'sim-node/1.0'},features:{parachute:true,parachuteFeedback:true,flightFailureDetection:true,takeoffReadiness:true,attitude:true,relativeYaw:true,linearAcceleration:false,gps:false,airspeed:false,barometer:false,stabilization:false,autopilot:false,servoFeedback:false,flightMixTransitions:false,transmitterBuzzerConfig:false},commands:['parachute.deploy'],maintenance:{authorized:false,expiresAt:0},units:{acceleration:'m/s2',angularVelocity:'deg/s',attitude:'deg',voltage:'V',pwm:'us'}};
export function faults(f:Frame,now:number,s:Settings){const list:{key:string;title:string;detail:string;source:string;severity:'warning'|'critical'}[]=[];if(f.safety?.flightFailure===true&&f.validity.safety==='valid'&&f.links.uart===true&&f.receivedAt&&now-Math.min(f.receivedAt,f.sampledAt??f.receivedAt)<=2000)list.push({key:'flight-failure',title:'Flight failure reported',detail:f.safety.failureReason??'Onboard firmware reported a flight failure. Recovery status is separate.',source:f.source==='DEMO'?'Simulator':'Firmware',severity:'critical'});if(f.receivedAt&&now-Math.min(f.receivedAt,f.sampledAt??f.receivedAt)>2000)list.push({key:'stale',title:'Telemetry is stale',detail:'Last sample is over two seconds old. Aircraft condition is unknown.',source:'Telemetry',severity:'critical'});for(const [key,failed,title,detail] of [['imu',f.imu===false,'IMU unavailable','No valid MPU6050 estimate.'],['uart',f.links.uart===false,'Nano UART link lost','Radio and actuator telemetry cannot be confirmed.'],['radio',f.links.radio===false,'Radio packet loss','Transmitter commands are not arriving reliably.']] as const)if(failed)list.push({key,title,detail,source:key.toUpperCase(),severity:'critical'});for(const [label,v,c] of [['Aircraft',f.aircraftVoltage,s.aircraftBattery],['Transmitter',f.transmitterVoltage,s.transmitterBattery]] as const)if(v!==null&&v<c.warning)list.push({key:'battery-'+label,title:label+' battery low',detail:`${fmt(v,2)} V · warning ${c.warning} V`,source:label,severity:v<c.critical?'critical':'warning'});const missing=['battery','surfaces','mixing','orientation','mechanical','failsafe'].filter(key=>!s.preflight[key]);if(missing.length)list.push({key:'preflight',title:'Preflight checks incomplete',detail:`${missing.length} operator checks remain. Automatic measurements do not replace physical inspection.`,source:'Preflight',severity:'warning'});return list}
export function seedRecordings():Recording[]{return [['Control-surface checkout','channels',60],['Gentle bank test','cruise',90],['Radio-loss simulation','radio',45]].map(([name,scenario,sec],i)=>{const createdAt=Date.UTC(2026,8,11,9+i,30),settings=structuredClone(defaultSettings);return {id:`demo-session-${i}`,name:String(name),notes:'Deterministic simulator data. Not a real flight.',createdAt,source:'DEMO',frames:Array.from({length:Number(sec)*5},(_,n)=>simulate(n/5,scenario as Scenario,settings,createdAt)),events:[],settings,seed:true}})}
export function csvFor(r:Recording){const columns=['time_utc','sequence','source','roll_deg','pitch_deg','accel_x_ms2','accel_y_ms2','accel_z_ms2','gyro_x_dps','gyro_y_dps','gyro_z_dps','aircraft_v','transmitter_v','throttle','left_us','right_us','flight_failure_reported','parachute_state','parachute_feedback'];const esc=(v:unknown)=>v==null?'':`"${String(v).replaceAll('"','""')}"`;return [columns.join(','),...r.frames.map(f=>[new Date(f.receivedAt).toISOString(),f.seq,f.source,f.attitude.roll,f.attitude.pitch,f.accel.x,f.accel.y,f.accel.z,f.gyro.x,f.gyro.y,f.gyro.z,f.aircraftVoltage,f.transmitterVoltage,f.outputs.throttle?.normalized,f.outputs.leftAileron?.pwm,f.outputs.rightAileron?.pwm,f.safety?.flightFailure,f.safety?.parachute?.state,f.safety?.parachute?.feedback].map(esc).join(','))].join('\n')}
export type CommandContext={environment:Environment;role:string;now:number;lastTelemetry:number;maintenance:boolean;armed:boolean|null;capabilities:string[];seen:boolean};
export function commandRejection(c:{expiresAt:number;kind:string},x:CommandContext){if(c.kind==='parachute.deploy')return 'Parachute requires a separate validated recovery workflow';if(x.environment!=='LIVE')return 'Environment cannot send hardware commands';if(!['owner','operator'].includes(x.role))return 'Operator permission required';if(x.seen)return 'Duplicate command';if(c.expiresAt<=x.now||c.expiresAt>x.now+5000)return 'Expired or invalid lifetime';if(!x.lastTelemetry||x.now-x.lastTelemetry>1500)return 'Fresh telemetry required';if(!x.maintenance||x.armed!==false)return 'Local maintenance and disarmed aircraft required';if(!x.capabilities.includes(c.kind))return 'Unsupported firmware capability';if(c.kind==='motor.test')return 'Motor test requires a separate validated onboard workflow';return null}
